### ISSUE TITLE
NameError: name 'xrange' is not defined. Did you mean: 'range'? - Python version issue?

### ISSUE THREAD

**Issue by wolfgangr** [HoWilgh/FCSpreadsheetTools#1]
Hi out there,

is there still anybody caring for FCSpreadsheetTools?

see:
https://forum.freecad.org/viewtopic.php?style=3&p=754693#p754693

```
02:43:35    File "/home/wrosner/.local/share/FreeCAD/Macro/SpreadsheetTools.FCMacro", line 373, in copy_to_clipboard
02:43:35      for r in xrange(nrows):
02:43:35  NameError: name 'xrange' is not defined. Did you mean: 'range'?
```

Macro version: 0.2.08
Last modified: 2017-11-03

FreeCAD 0.21.2

as pointed out by forum user onekk, this might be Python2 / Python3 compatibility issue

**Comment by wolfgangr** [comment]
assume the project is orphaned?
forked it and will give it a try:
https://github.com/wolfgangr/FCSpreadsheetTools

If anybody else is working on it, please lets get in contact to avoid redundant work.

**Comment by HoWilgh** [comment]
@wolfgangr, no I did not use it for years. 
Cool if you can use it and if it is only the one Python2 / Python3 compatibility issue

**Comment by wolfgangr** [comment]
Hi, Wilfried,

nice to find you alive and in healthy condition, obvioulsy ;-)

Well, yes, there seems to be more to it than just changing "xrange" to "range".
Following python doc, this should be a straightforward no-brainer.

now I get
```
...~/.local/share/FreeCAD/Macro/SpreadsheetTools.FCMacro", line 269, in paste_from_clipboard
      for n_line, line in zip(range(n_cells), cbtext_split[0:n_cells]):
  TypeError: 'float' object cannot be interpreted as an integer
```

I think that that in the process of merging @realthunder 's "Link fork", spreadsheet enjoyed a huge progress in functionality, which, of course might trigger regression bugs.

I'll go and try to understand your code now...

**Comment by wolfgangr** [comment]
I think that shit happens somewhere between line 257 and 337 - where the paste is going on.

after fixing the xrange issue, I get (sometimes)

```
...~/FreeCAD/Macro/SpreadsheetTools.FCMacro", line 269, in paste_from_clipboard
      for n_line, line in zip(range(n_cells), cbtext_split[0:n_cells]):
  TypeError: 'float' object cannot be interpreted as an integer
```

from the code lines before (well, I'm no python crack at all ...) I can't imagine where a float could arise.

other times (may be when there are no numbers in the source selection?)
 I get pasted the format string as in the clipboard 4 cells below the actual selected paste area.

Looks like I have to learn debugging FreeCAD python macros to see what's going on....

**Comment by wolfgangr** [comment]
OK, after gleaning over the code, I see that simple replacement of `xrange`to `range` might have restored some of it's previous behaviour.

It is in "works for me" condition and looks like it does what I want, if I carefully play with the tickmarks.

I think to keep it as part of "1.0", some investment into the maturity of the code might be fine.
Any need for that? If not, I'll leave it for now.
